# Generated by Django 5.2.3 on 2025-07-03 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.ImageField(upload_to='hair_photos')),
                ('back', models.ImageField(upload_to='hair_photos')),
                ('up_front', models.ImageField(upload_to='hair_photos')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(default=0)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('subsciption_expires_on', models.DateTimeField(blank=True, null=True)),
                ('subscription_status', models.CharField(default='freemium', max_length=100)),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_provider', models.CharField(default='normal', max_length=20)),
                ('hair_porosity', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_texture', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_density', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_growth_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_concerns', models.CharField(blank=True, max_length=100, null=True)),
                ('current_hair_product', models.CharField(blank=True, max_length=100, null=True)),
                ('current_conditioner', models.CharField(blank=True, max_length=100, null=True)),
                ('current_styling_product', models.CharField(blank=True, max_length=100, null=True)),
                ('current_product_satisfection', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_goals', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_elasticity', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_thickness', models.CharField(blank=True, max_length=100, null=True)),
                ('checmical_treatment', models.CharField(blank=True, max_length=100, null=True)),
                ('heat_tool_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('scalp_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('climate', models.CharField(blank=True, max_length=100, null=True)),
                ('water_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_factors', models.CharField(blank=True, max_length=100, null=True)),
                ('lifestyle_factors', models.CharField(blank=True, max_length=100, null=True)),
                ('styling_habits', models.CharField(blank=True, max_length=100, null=True)),
                ('styling_method_regularly_used', models.CharField(blank=True, max_length=100, null=True)),
                ('how_often_wear_protective_wears', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_photos', models.ManyToManyField(blank=True, to='accounts.hairphoto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
