# Generated by Django 5.2.3 on 2025-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_provider',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
