# Generated by Django 5.2.3 on 2025-06-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_routine', models.TextField(blank=True, null=True)),
                ('monthly_routine', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(blank=True, max_length=100, null=True)),
                ('step_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HairAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_report', models.TextField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_analysis_and_tips.routine')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='washday',
            field=models.ManyToManyField(blank=True, null=True, to='hair_analysis_and_tips.washday'),
        ),
    ]
