# Generated by Django 5.2.3 on 2025-07-03 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_estimate', models.CharField(max_length=20)),
                ('scalp_visibility', models.TextField()),
                ('protective_style', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HairCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('insight', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HairRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_routine', models.JSONField()),
                ('monthly_routine', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HairTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField()),
                ('characteristics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hair_analysis_and_tips.characteristics')),
                ('conditions', models.ManyToManyField(to='hair_analysis_and_tips.haircondition')),
                ('hair_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hair_analysis_and_tips.hairtype')),
            ],
        ),
        migrations.CreateModel(
            name='HairAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_analysis_and_tips.analysisreport')),
                ('hair_photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hairphoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_analysis_and_tips.hairroutine')),
                ('tips', models.ManyToManyField(to='hair_analysis_and_tips.hairtip')),
            ],
        ),
        migrations.AddField(
            model_name='hairroutine',
            name='washday_steps',
            field=models.ManyToManyField(to='hair_analysis_and_tips.routinestep'),
        ),
    ]
