# Generated by Django 5.2.3 on 2025-06-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_subscription_id_and_more'),
        ('hair_analysis_and_tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairanalysis',
            name='hair_photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hairphoto'),
        ),
    ]
